### ISSUE TITLE
Missing error handler?

### ISSUE THREAD

**Issue by qha** [jcpunk/puppet-efi#3]
One of our hosts the secure_boot_enabled fact sometimes produces the message below (0-4 times per day, 2 on average, where one day would typically see 48 invocations).

"(Facter) Error while resolving custom fact fact='secure_boot_enabled', resolution='<anonymous>': Invalid argument @ io_fread - /sys/firmware/efi/efivars/SecureBoot-*uuid*"

The *uuid* is always the same in the error messages and corresponds to a file that exists and can be read (at least) when the fact does not report an error.

Since eperm and eaccess are just silently dropped perhaps einval could be treated the same way?

**Comment by jcpunk** [comment]
New version 0.1.2 should have the extra error handling.

**Comment by qha** [comment]
Great, thanks! I will try to test it this week.

**Comment by jcpunk** [comment]
Any news?

**Comment by qha** [comment]
Sorry, i got swamped with other things and completely forgot. I'll try to test it next week, this time i've made a note of it in my calendar.

**Comment by qha** [comment]
One of my collegues upgraded the module on friday before i had even opened a merge request for it and since then there have been no errors reported.

Thanks again!
